#! /usr/bin/env bash
set -e

curl \
-H'Request URL: http://127.0.0.1:8080' \
-H'Request method: POST' \
-H'Content-Type: application/json' \
-H'X-GitHub-Delivery: 9f52dd65-6048-4a32-981d-9fdb6c9dc869' \
-H'X-GitHub-Event: push' \
-H'X-GitHub-Event-Type: push' \
-H'X-Gitea-Delivery: 9f52dd65-6048-4a32-981d-9fdb6c9dc869' \
-H'X-Gitea-Event: push' \
-H'X-Gitea-Event-Type: push' \
-H'X-Gitea-Signature: 3977ade52a97a627a8a62914ddff4ca563293cec1b0404c4d01388fc1a3ed36b' \
-H'X-Gogs-Delivery: 9f52dd65-6048-4a32-981d-9fdb6c9dc869' \
-H'X-Gogs-Event: push' \
-H'X-Gogs-Event-Type: push' \
-H'X-Gogs-Signature: 3977ade52a97a627a8a62914ddff4ca563293cec1b0404c4d01388fc1a3ed36b' \
-H'X-Hub-Signature: sha1=038803a16119da6c78f84ddb4ed1f02488717908' \
-H'X-Hub-Signature-256: sha256=3977ade52a97a627a8a62914ddff4ca563293cec1b0404c4d01388fc1a3ed36b' \
-d'{
  "ref": "refs/heads/master",
  "before": "082f0a78a1f9116440c015faeb3d0ee4fc191a04",
  "after": "082f0a78a1f9116440c015faeb3d0ee4fc191a04",
  "compare_url": "https://git.corpix.org/corpix/test/compare/082f0a78a1f9116440c015faeb3d0ee4fc191a04...082f0a78a1f9116440c015faeb3d0ee4fc191a04",
  "commits": [
    {
      "id": "082f0a78a1f9116440c015faeb3d0ee4fc191a04",
      "message": "init\n",
      "url": "https://git.corpix.org/corpix/test/commit/082f0a78a1f9116440c015faeb3d0ee4fc191a04",
      "author": {
        "name": "Dmitry Moskowski",
        "email": "me@corpix.ru",
        "username": ""
      },
      "committer": {
        "name": "Dmitry Moskowski",
        "email": "me@corpix.ru",
        "username": ""
      },
      "verification": null,
      "timestamp": "0001-01-01T00:00:00Z",
      "added": null,
      "removed": null,
      "modified": null
    }
  ],
  "total_commits": 1,
  "head_commit": {
    "id": "082f0a78a1f9116440c015faeb3d0ee4fc191a04",
    "message": "init\n",
    "url": "https://git.corpix.org/corpix/test/commit/082f0a78a1f9116440c015faeb3d0ee4fc191a04",
    "author": {
      "name": "Dmitry Moskowski",
      "email": "me@corpix.ru",
      "username": ""
    },
    "committer": {
      "name": "Dmitry Moskowski",
      "email": "me@corpix.ru",
      "username": ""
    },
    "verification": null,
    "timestamp": "0001-01-01T00:00:00Z",
    "added": null,
    "removed": null,
    "modified": null
  },
  "repository": {
    "id": 14,
    "owner": {
      "id": 1,
      "login": "corpix",
      "login_name": "",
      "full_name": "",
      "email": "me@corpix.ru",
      "avatar_url": "https://git.corpix.org/avatars/7c3449eb50757312a39669a2a8aaf0d5",
      "language": "",
      "is_admin": false,
      "last_login": "0001-01-01T00:00:00Z",
      "created": "2022-11-20T16:18:17Z",
      "restricted": false,
      "active": false,
      "prohibit_login": false,
      "location": "",
      "website": "https://corpix.dev",
      "description": "",
      "visibility": "limited",
      "followers_count": 0,
      "following_count": 0,
      "starred_repos_count": 0,
      "username": "corpix"
    },
    "name": "test",
    "full_name": "corpix/test",
    "description": "",
    "empty": false,
    "private": false,
    "fork": false,
    "template": false,
    "parent": null,
    "mirror": false,
    "size": 27,
    "language": "",
    "languages_url": "https://git.corpix.org/api/v1/repos/corpix/test/languages",
    "html_url": "https://git.corpix.org/corpix/test",
    "ssh_url": "ssh://gitea@git.corpix.org:2222/corpix/test.git",
    "clone_url": "https://git.corpix.org/corpix/test.git",
    "original_url": "",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 1,
    "open_issues_count": 0,
    "open_pr_counter": 0,
    "release_counter": 0,
    "default_branch": "master",
    "archived": false,
    "created_at": "2023-01-21T19:13:22Z",
    "updated_at": "2023-01-21T19:17:00Z",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": false
    },
    "has_issues": true,
    "internal_tracker": {
      "enable_time_tracker": true,
      "allow_only_contributors_to_track_time": true,
      "enable_issue_dependencies": true
    },
    "has_wiki": true,
    "has_pull_requests": true,
    "has_projects": true,
    "ignore_whitespace_conflicts": false,
    "allow_merge_commits": true,
    "allow_rebase": true,
    "allow_rebase_explicit": true,
    "allow_squash_merge": true,
    "allow_rebase_update": true,
    "default_delete_branch_after_merge": false,
    "default_merge_style": "merge",
    "avatar_url": "",
    "internal": false,
    "mirror_interval": "",
    "mirror_updated": "0001-01-01T00:00:00Z",
    "repo_transfer": null
  },
  "pusher": {
    "id": 1,
    "login": "corpix",
    "login_name": "",
    "full_name": "",
    "email": "me@corpix.ru",
    "avatar_url": "https://git.corpix.org/avatars/7c3449eb50757312a39669a2a8aaf0d5",
    "language": "",
    "is_admin": false,
    "last_login": "0001-01-01T00:00:00Z",
    "created": "2022-11-20T16:18:17Z",
    "restricted": false,
    "active": false,
    "prohibit_login": false,
    "location": "",
    "website": "https://corpix.dev",
    "description": "",
    "visibility": "limited",
    "followers_count": 0,
    "following_count": 0,
    "starred_repos_count": 0,
    "username": "corpix"
  },
  "sender": {
    "id": 1,
    "login": "corpix",
    "login_name": "",
    "full_name": "",
    "email": "me@corpix.ru",
    "avatar_url": "https://git.corpix.org/avatars/7c3449eb50757312a39669a2a8aaf0d5",
    "language": "",
    "is_admin": false,
    "last_login": "0001-01-01T00:00:00Z",
    "created": "2022-11-20T16:18:17Z",
    "restricted": false,
    "active": false,
    "prohibit_login": false,
    "location": "",
    "website": "https://corpix.dev",
    "description": "",
    "visibility": "limited",
    "followers_count": 0,
    "following_count": 0,
    "starred_repos_count": 0,
    "username": "corpix"
  }
}' http://127.0.0.1:8080
